### ISSUE TITLE
java.lang.SecurityException: Prohibited package name: java.sql

### ISSUE THREAD

**Issue by usr-ein** [CookieCadger/CookieCadger#33]
Hello,
I'm running macOS V 10.12.6 with java version "9.0.1" and JRE (build 9.0.1+11), and when I run Cookie Cadger 1.08 using `java -jar CookieCadger-1.08.jar` I got this exception:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.cookiecadger.MacSupport (rsrc:./) to method com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of com.cookiecadger.MacSupport
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-0" java.lang.SecurityException: Prohibited package name: java.sql
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:889)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.cookiecadger.Program$2.run(Program.java:92)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I tried resolving the issue by myself but didn't find any solution to get it working. I am using the latest version of Java available on my platform.
Furthermore, it seems to be an issue related to `java.sql`, which I assumed to be related to JDBC but apparently JDBC is already installed so I don't understand.

**Comment by Jack-zhangtaotao** [comment]
switch java10 to java8

**Comment by theerasergun123** [comment]
how to switch @Jack-zhangtaotao
